package config

var (
	HOST_POST               = "HOST_POST"
	HOST_POST_DEFAULT_VALUE = ":8080"
	DATASOURCE_USERNAME     = "DATASOURCE_USERNAME"
	DATASOURCE_PASSWORD     = "DATASOURCE_PASSWORD"
	DATASOURCE_URL          = "DATASOURCE_URL"
)
